version: "2"
services:
  app:
      depends_on:
        - database
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 80:80
        - 443:443
      environment:
        DB_HOST: database
        DB_PORT: 5432
        APP_KEY: 'base64:qm/UMbvRiN5lnWtzWNSS6QNfh5z845Fp39j+9tZoKeo='
        DB_DATABASE: hidoctor
        DB_USERNAME: hidoctoruser
        DB_PASSWORD: hidoctorpassword
      volumes:
        - ./storage:/var/www/html/storage

  database:
    image: "mdillon/postgis"
    container_name: "hi_doctor"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hidoctoruser
      - POSTGRES_PASSWORD=hidoctorpassword
      - POSTGRES_DB=hidoctor
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
